# Generated by Django 4.2.7 on 2025-04-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
