# Generated by Django 4.2.7 on 2025-05-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_make_journey_fields_required'),
        ('tracker', '0002_add_journey_to_locationupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationupdate',
            name='journey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='blog.journey'),
            preserve_default=False,
        ),
    ]
